pg: &defaults
  adapter: postgresql

development:
  database: jtop_dev
  adapter: postgresql

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  adapter: postgresql
  database: jtop_test

production:
  adapter: postgresql
  database: db/JTopStats_production.db

